default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: 1234567

development:
  <<: *default
  database: handymate_development

test:
  <<: *default
  database: handymate_test

production:
  <<: *default
  database: handymate_production
  username: handymate
  password: <%= ENV["HANDYMATE_DATABASE_PASSWORD"] %>
